version: "3.9"

services:
  authserver:
    image: lakhansamani/authorizer:1.1.37
    environment:
      - ADMIN_SECRET=admin123!
      - DATABASE_URL=mongodb://root:admin123!@authdb:27017/
      - DATABASE_TYPE=mongodb
      - AUTHORIZER_URL=http://localhost:8081
      - ENV=production
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USERNAME=admin@rfiready.co
      - SMTP_PASSWORD=Admin123!!
      - SENDER_EMAIL=admin@rfiready.co
      - RESET_PASSWORD_URL=http://localhost:8081/resetpassword
      - DISABLE_MAGIC_LINK_LOGIN=true
      - DISABLE_EMAIL_VERIFICATION=true
      - ORGANIZATION_NAME=RFIReady
      - ORGANIZATION_LOGO=https://rfireadyasset.s3.amazonaws.com/logo.png
      - LINKEDIN_CLIENT_ID=77jyah3dfw7kz3
      - LINKEDIN_CLIENT_SECRET=PzXxPYTV6arIdpMW
      - ROLES=user,customer,vendor,admin
      - DEFAULT_ROLES=customer
      - REDIS_URL=redis://redis:7000
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
    ports:
      - 8081:8080
    depends_on:
      - authdb
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --fail localhost:8080 || exit 1"]
    #   interval: 60s
    #   retries: 5
    #   timeout: 10s
    networks:
      - api-service

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000
    ports:
      - 7000:7000
    networks:
      - api-service

  authdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123!
    ports:
      - 27018:27017
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
    # healthcheck:
    #   test: ["CMD-SHELL", "curl localhost:27018/test || exit 1"]
    #   interval: 60s
    #   retries: 5
    #   timeout: 10s
    networks:
      - api-service

networks:
  api-service:
    external: true
