version: "3.9"

services:
  authserver:
    image: rfiready.co:5000/authserver:${DEP_ENV}
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /root
    environment:
      - DATABASE_URL=mongodb://root:admin123!@authdb:27017/
      - DATABASE_TYPE=mongodb
      - AUTHORIZER_URL=https://www.admin.rfiready.co
      - ENV=production
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USERNAME=admin@rfiready.co
      - SMTP_PASSWORD=Admin123!!
      - SENDER_EMAIL=admin@rfiready.co
      - RESET_PASSWORD_URL=https://www.rfiready.co/resetpassword
      - DISABLE_MAGIC_LINK_LOGIN=true
      - DISABLE_EMAIL_VERIFICATION=true
      - ORGANIZATION_NAME=RFIReady
      - ORGANIZATION_LOGO=https://rfireadyasset.s3.amazonaws.com/logo.png
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
    ports:
      - 8081:8080
    depends_on:
      - authdb
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --fail localhost:8080 || exit 1"]
    #   interval: 60s
    #   retries: 5
    #   timeout: 10s
    networks:
      - api-service

  authdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123!
    ports:
      - 27018:27017
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
    # volumes:
    #   - type: volume
    #     source: authdata
    #     target: /data/db
    #     volume:
    #       nocopy: true
    # healthcheck:
    #   test: ["CMD-SHELL", "curl localhost:27018/test || exit 1"]
    #   interval: 60s
    #   retries: 5
    #   timeout: 10s
    networks:
      - api-service

networks:
  api-service:
    external: true
volumes:
  authdata:
    driver_opts:
      type: nfs4
      o: "addr=172.31.84.217,nolock,rw"
      device: ":/root/nfs/auth/data"
